"""inittial migration1

Revision ID: c9acb64178e4
Revises: d469f0370dc0
Create Date: 2024-12-14 00:13:17.486835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9acb64178e4'
down_revision: Union[str, None] = 'd469f0370dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'abc_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('abc_test', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
