"""inittial migration1

Revision ID: d469f0370dc0
Revises: 64075df5f7bc
Create Date: 2024-11-28 15:39:29.884537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd469f0370dc0'
down_revision: Union[str, None] = '64075df5f7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('abc_test', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'abc_test')
    # ### end Alembic commands ###
